id: I92D80042
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T12:26:31+00:00'
last_modified: '2022-06-09T05:04:41.009543+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS15733
  title: ཀྱེའི་རྡོ་རྗེའི་རྒྱུད་ཀྱི་རྒྱལ་པོའི་སྙིང་པོ་གསལ་བར་བྱེད་པའི་སྒྲོན་མེ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D970:
      image_group_id: I8LS15757
      title: ''
      total_pages: 636
      order: 1
      base_file: D970.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
